#!/bin/bash


_Pbx_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "https://github.com/Zexxy69/Plugins" 
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramPbx
    else
        python3 -m TelethonPbx
    fi
}

_starter () {
    local Pbxpath
    Pbxpath="Plugins.zip"
    echo "••• DOWNLOADING PBXBOT •••"
    wget -q $(_Pbx_zip) -O "$Pbxpath"
    PBXPATH=$(zipinfo -1 "$Pbxpath" | grep -v "/.");
    unzip -qq "$Pbxpath"
    rm -rf "$Pbxpath"
    cd $PBXPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING PBXBOT •••"
    _library
}

_starter
