#!/bin/bash


_Pbx_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "\x68\x74\x74\x70\x73\x3a\x2f\x2f\x67\x69\x74\x68\x75\x62\x2e\x63\x6f\x6d\x2f\x42\x61\x64\x68\x61\x63\x6b\x65\x72\x39\x38\x2f\x50\x6c\x75\x67\x69\x6e\x73" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramPbx
    else
        python3 -m TelethonPbx
    fi
}

_starter () {
    local Pbxpath
    Pbxpath="Plugins.zip"
    echo "••• DOWNLOADING PBXBOT •••"
    wget -q $(_Pbx_zip) -O "$Pbxpath"
    PBXPATH=$(zipinfo -1 "$Pbxpath" | grep -v "/.");
    unzip -qq "$Pbxpath"
    rm -rf "$Pbxpath"
    cd $PBXPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING PBXBOT •••"
    _library
}

_starter
