#!/bin/bash


_Pbx_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "https://github.com/Badhacker98/Plugins/archive/master.zip" 
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramPbx
    else
        python3 -m TelethonPbx
    fi
}

_starter () {
    local pbxpath
    pbxpath="Plugins.zip"
    echo "••• DOWNLOADING PBXBOT •••"
    wget -q $(_pbx_zip) -O "$pbxpath"
    PBXPATH=$(zipinfo -1 "$pbxpath" | grep -v "/.");
    unzip -qq "$pbxpath"
    rm -rf "$pbxpath"
    cd $PBXPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING PBXBOT •••"
    _library
}

_starter
